In [1]:
import numpy as np
from sklearn.feature_selection import VarianceThreshold

In [5]:
# Carga de datos.
X = [[0, 0, 1], [0, 1, 0], [1, 0, 0],
     [0, 1, 1], [0, 1, 0], [0, 1, 1]]
print(np.array(X))

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]]


: 

In [3]:
# Limpieza de datos: selección de atributos.

# fijamos un umbral (th) para decidir qué porcentaje mínimo deben variar los valores de una columna para considerarse 
# una columna relevante a la hora de mantenerla en nuestro estudio
th = 0.2
sel = VarianceThreshold(th)
print(sel.fit_transform(X))

[[0 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]]
